name: Start json-server
on:
  push:
    jobs:
      build-node:
        runs-on: ubuntu-latest
        container: node:16
        steps:
          - uses: actions/checkout@v4
          - run: npm install
          - run: npm run dev
          - run: node index.js
